services:
  db:
    image: postgres:16
    container_name: boardgames-db
    environment:
      POSTGRES_DB: boardgamesdb
      POSTGRES_USER: boardgames_user
      POSTGRES_PASSWORD: boardgames_pass
    ports:
      - "5432:5432"
    volumes:
      - boardgames_data:/var/lib/postgresql/data

volumes:
  boardgames_data: