app.base-url=http://localhost:8080/
app.frontend.base-url=http://localhost:5173/

app.cors.allowed-origins=http://localhost:5173

google.oauth.client-id=471546944671-8rvlp7dhlrk0t71c9dkv395aliork59s.apps.googleusercontent.com
