spring.application.name=boardgames
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/boardgamesdb
spring.datasource.username=boardgames_user
spring.datasource.password=boardgames_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect