app.base-url=https://boardgames.motomutterers.com/
app.frontend.base-url=https://boardgames.motomutterers.com/

app.cors.allowed-origins=https://boardgames.motomutterers.com

google.oauth.client-id=471546944671-8rvlp7dhlrk0t71c9dkv395aliork59s.apps.googleusercontent.com
